import {
	BsCheck as Accept,
	BsListCheck as AddCheckbox,
	BsCodeSlash as AddCode,
	BsCalendarPlus as AddDate,
	BsTypeH3 as AddHeading,
	BsImage as AddImage,
	BsListUl as AddListItem,
	BsArrowLeft as ArrowLeft,
	BsArrowRight as ArrowRight,
	BsArrowLeft as BackButton,
	BsTypeBold as Bold,
	BsCalendarRange as Calendar,
	BsChat as Chat,
	BsFillCheckSquareFill as Checked,
	BsChevronDown as ChevronDown,
	BsChevronLeft as ChevronLeft,
	BsChevronRight as ChevronRight,
	BsChevronUp as ChevronUp,
	BsPaperclip as Clip,
	BsClock as Clock,
	BsFiles as Copy,
	BsTrash as Delete,
	BsCalendarMinus as DeleteDate,
	BsPencil as Edit,
	BsPersonCircle as EmptyAvatar,
	BsEyeSlash as Hide,
	BsHouse as Home,
	BsQuestionCircle as Info,
	BsTypeItalic as Italic,
	BsLink45Deg as Link,
	BsMarkdown as Markdown,
	BsMoonStars as Moon,
	BsPlusCircle as New,
	BsSquare as NotChecked,
	BsCheck2 as Ok,
	BsPauseCircle as Pause,
	BsPercent as Percent,
	BsPerson as Person,
	BsPinAngle as Pin,
	BsPlayCircle as Play,
	BsTrophy as Pro,
	BsEyeglasses as ReadMode,
	BsArrowReturnLeft as Return,
	BsGear as Settings,
	BsDoorOpen as SignOut,
	BsStopCircle as Stop,
	BsSun as Sun,
	BsThreeDotsVertical as ThreeDots,
} from 'react-icons/bs';

export const Icons = {
	Italic,
	AddHeading,
	Bold,
	Markdown,
	Sun,
	Moon,
	Home,
	Link,
	Pin,
	Delete,
	AddDate,
	DeleteDate,
	ReadMode,
	AddCheckbox,
	AddListItem,
	AddImage,
	AddCode,
	Checked,
	NotChecked,
	Info,
	Pro,
	Calendar,
	ChevronLeft,
	ChevronRight,
	Clip,
	ThreeDots,
	Person,
	Percent,
	Chat,
	EmptyAvatar,
	BackButton,
	Ok,
	Copy,
	New,
	Edit,
	Play,
	Pause,
	Settings,
	Hide,
	Accept,
	Return,
	Clock,
	Stop,
	ArrowRight,
	ArrowLeft,
	SignOut,
	ChevronDown,
	ChevronUp,
};
