import {
	BsCheck as Accept,
	BsListCheck as AddCheckbox,
	BsCodeSlash as AddCode,
	BsCalendarPlus as AddDate,
	BsImage as AddImage,
	BsListUl as AddListItem,
	BsArrowLeft as ArrowLeft,
	BsArrowRight as ArrowRight,
	BsArrowLeft as BackButton,
	BsCalendarRange as Calendar,
	BsChat as Chat,
	BsFillCheckSquareFill as Checked,
	BsChevronLeft as ChevronLeft,
	BsChevronRight as ChevronRight,
	BsPaperclip as Clip,
	BsClock as Clock,
	BsCurrencyDollar as Coin,
	BsFiles as Copy,
	BsTrash as Delete,
	BsCalendarMinus as DeleteDate,
	BsBoxArrowInDown as Deposit,
	BsPencil as Edit,
	BsPersonCircle as EmptyAvatar,
	BsEyeSlash as Hide,
	BsHouse as Home,
	BsQuestionCircle as Info,
	BsLink45Deg as Link,
	BsList as Menu,
	BsMoonStars as Moon,
	BsPlusCircle as New,
	BsSquare as NotChecked,
	BsCheck2 as Ok,
	BsPauseCircle as Pause,
	BsPercent as Percent,
	BsPerson as Person,
	BsPinAngle as Pin,
	BsPlayCircle as Play,
	BsTrophy as Pro,
	BsEyeglasses as ReadMode,
	BsArrowReturnLeft as Return,
	BsGear as Settings,
	BsDoorOpen as SignOut,
	BsStopCircle as Stop,
	BsSun as Sun,
	BsThreeDotsVertical as ThreeDots,
	BsWallet2 as Wallet,
	BsBoxArrowUpRight as Withdraw,
} from 'react-icons/bs';

// TODO: ESize
const SIZE = {
	SMALL: 16,
	MEDIUM: 20,
	BIG: 24,
};

export const Icons = {
	Sun,
	Moon,
	Home,
	Link,
	Pin,
	Delete,
	AddDate,
	DeleteDate,
	ReadMode,
	AddCheckbox,
	AddListItem,
	AddImage,
	AddCode,
	Checked,
	NotChecked,
	Info,
	Pro,
	Calendar,
	ChevronLeft,
	ChevronRight,
	Clip,
	ThreeDots,
	Person,
	Percent,
	Chat,
	Menu,
	Coin,
	EmptyAvatar,
	BackButton,
	Ok,
	Copy,
	New,
	Edit,
	Play,
	Pause,
	Settings,
	Hide,
	Accept,
	Return,
	Clock,
	Stop,
	ArrowRight,
	ArrowLeft,
	Wallet,
	Deposit,
	Withdraw,
	SignOut,
	SIZE,
};
