name: Semantic release

on: push
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm install
            - name: Build npm package lib
              run: npm run build
            - name: Semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
            - name: github pages
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  BRANCH: main # The branch the action should deploy to.
                  FOLDER: docs-build # The folder that the build-storybook script generates files.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
                  TARGET_FOLDER: docs # The folder that we serve our Storybook files from
